services:
  - type: web
    name: mercato-transfer-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: mercato-transfer-platform
          property: port
    healthCheckPath: /
    autoDeploy: true
    branch: main
